[general]
version = "0.2.0"

[problem]
problem_name = "ahc045"
objective = "Min"
score_regex = '(?m)^\s*Score\s*=\s*(?P<score>\d+)\s*$'

[test]
start_seed = 0
end_seed = 100
threads = 0
out_dir = "./pahcer"

# ==============================
#         COMPILE STEPS
# ==============================

# Python なのでビルド不要
compile_steps = []

# ==============================
#           TEST STEPS
# ==============================

# Run the tester with the Python solution
[[test.test_steps]]
program = "cargo"
args = [
    "run",
    "-r",
    "--bin",
    "tester",
    "--",
    "python3",
    "../main.py"
]
stdin = "./tools/in/{SEED04}.txt"
stdout = "./tools/out/{SEED04}.txt"
stderr = "./tools/err/{SEED04}.txt"
current_dir = "./tools"
measure_time = true

# Run the visualizer to calculate the score
[[test.test_steps]]
program = "cargo"
args = [
    "run",
    "--bin",
    "vis",
    "--release",
    "./in/{SEED04}.txt",
    "./out/{SEED04}.txt"
]
current_dir = "./tools"
measure_time = false
